---
- name: Wait SSH
  hosts: all
  gather_facts: False
  tasks:
    - name: "Wait 180 seconds, start checking after 10 seconds"
      wait_for_connection:
        delay: 10
        timeout: 180
        connect_timeout: 10
        sleep: 5
- name: Configure KVM base image
  hosts: all
  gather_facts: True
  roles:
    - common
