---
- name: Wait SSH
  hosts: all
  gather_facts: False
  tasks:
    - name: "Wait 300 seconds, start checking after 15 seconds"
      wait_for_connection:
        delay: 15
        timeout: 300
        connect_timeout: 10
        sleep: 5
- name: Configure KVM base image
  hosts: all
  gather_facts: True
  roles:
    - common
